export const projects = [
  {
    id: "1",
    name: "Piratas do Caribe - Filmes",
    images: [
      "piratas-do-caribe-1.jpg",
      "piratas-do-caribe-2.jpg",
      "piratas-do-caribe-3.jpg",
      "piratas-do-caribe-4.jpg",
      "piratas-do-caribe-5.jpg",
      "piratas-do-caribe-6.jpg",
    ],
    description: "Aplicativo multi-tela com o tema Piratas do Caribe que exibe informações a respeito dos 5 filmes da franquia (título, imagem e sinopse)",
    technicals: [
      "Navegação de Telas",
      "Componentização de telas",
      "Funcionalidade de scroll",
      "Estilização e tratamento de imagens",
      "Flexbox para alinhamento de elementos",
      "Conceitos de experiência do usuário",
      "Design adaptado voltado telas menores",
      "Eventos de clique",
      "Efeito de sombra em textos",
    ],
    components: [
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "ScrollView",
      "SafeAreaView",
      "StyleSheet",
      "NavigationContainer",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/piratas-do-caribe---filmes?platform=android",
  },
  {
    id: "2",
    name: "Formulário",
    images: [
      "formulario-1.jpg",
      "formulario-2.jpg",
      "formulario-3.jpg",
      "formulario-4.jpg",
    ],
    description: "Formulário com validação que recebe dados de um usuário (nome, ano de nascimento, endereço, CPF e RG. Após o formulário ser submitado, o usuário é redirecionado para a segunda tela do aplicativo, mostrando seus dados inseridos em formato de tabela, juntamento com sua idade, calculada a partir do ano de nascimento fornecido",
    technicals: [
      "Construção de formulários em React",
      "Uso de states para alterar componentes dinamicamente",
      "Validação de dados com REGEX (expressões regulares)",
      "Passagem de dados entre telas por meio de parâmetros de rota",
      "Fluxo de renderização",
      "Mensagens de alerta",
      "Renderização e estilização condicional",
      "Experiência de usuário no que diz respeito a preencher formulários em dispositivos móveis"
    ],
    components: [
      "StyleSheet",
      "View",
      "Text",
      "TextInput",
      "SafeAreaView",
      "TouchableOpacity",
      "TouchableWithoutFeedback",
      "Keyboard",
      "Alert"
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/formulario?platform=android",
  },
  {
    id: "3",
    name: "RPG Card",
    images: [
      "rpg-card-1.jpg",
      "rpg-card-2.jpg",
    ],
    description: "Card de personagem estilo RPG, contendo informações como nome, classe, nível, atributos de força, ataque, resistência e velociade. O card é adaptado para ser visualizado com a tela tanto em posição de paisagem quanto de retrato, podendo o usuário mudar para uma das duas posições ao pressionar o botão que contém uma seta",
    technicals: [
      "Estilização condicional",
      "Manipulação da orientação da tela com Expo",
      "Captura da largura e altura da tela do dispositivo",
      "Posição absoluta de elementos",
      "Flexbox para alinhamento de elementos",
      "Componentização do layout",
      "Separação de pastas para cada componente",
      "Ícones em React",
      "Passagem de dados entre componentes",
    ],
    components: [
      "StyleSheet",
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "useWindowDimensions",
      "ScreenOrientation",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/card-rpg?platform=android",
  },
  {
    id: "4",
    name: "Família Simpsons",
    images: [
      "familia-simpson-1.jpg",
      "familia-simpson-2.jpg",
      "familia-simpson-3.jpg",
      "familia-simpson-4.jpg",
      "familia-simpson-5.jpg",
      "familia-simpson-6.jpg",
    ],
    description: "Aplicativo sobre os integrantes da família Simpson, que informações descritivas da cada personagem. Apenas possui 2 telas: uma que contém os cards referentes a cada Simpson, e outra que exibe os dados do personagem escolhido pelo usuário dinamicamente",
    technicals: [
      "Renderização em lista com FlatList",
      "Uso da função map do JavaScript para renderizar itens dinamicamente",
      "Passagem de dados entre componentes através de propriedades e de parâmetros de rotas",
      "Conceito de elevação de state",
      "Cópia de dados de arrays para componentes usndo o spread operator",
      "Inserção de elementos filhos em um componente",
      "Estilização condicional a partir de propriedades de componentes",
      "Estilização da barra de status do dispositivo",
      "Consumo de dados de um arquivo JavaScript externo",
    ],
    components: [
      "FlatList",
      "StatusBar",
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/familia-simpson?platform=android",
  },
  {
    id: "5",
    name: "Card de apresentação profissional",
    images: [
      "card-profissional-1.jpg",
      "card-profissional-2.jpg",
    ],
    description: "Card de apresentação profissional de programador fictício. Inicialmente, o card exibe imagem, nome, e-mail e telefone de contato, porém ao clicar no botão de expandir, é acrescido as tecnologias (cada uma com uma respectiva cor) que o programador domina, além de botões de enviar mensagem e contratá-lo",
    technicals: [
      "Uso de funções para renderizações dinâmicas",
      "Passagem de funções entre componntes",
      "Uso de containers como componentes globais",
      "Imagens de Fundo em React",
      "Manipulação de opacidade de views",
      "Manipulação de overflow de elementos",
      "Desestruturação de objetos JavaScript",
      "Uso de bibliotecas React para ícones",
    ],
    components: [
      "Image",
      "ImageBackground",
      "View",
      "Text",
      "TouchableOpacity",
      "StatusBar",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/profile-card?platform=android",
  },
];
