export const projects = [
  {
    id: "1",
    name: "Piratas do Caribe - Filmes",
    images: [
      "piratas-do-caribe-1.jpg",
      "piratas-do-caribe-2.jpg",
      "piratas-do-caribe-3.jpg",
      "piratas-do-caribe-4.jpg",
      "piratas-do-caribe-5.jpg",
      "piratas-do-caribe-6.jpg",
    ],
    description:
      "Aplicativo multi-tela com o tema Piratas do Caribe que exibe informações a respeito dos 5 filmes da franquia (título, imagem e sinopse)",
    technicals: [
      "Navegação de Telas",
      "Componentização de telas",
      "Funcionalidade de scroll",
      "Estilização e tratamento de imagens",
      "Flexbox para alinhamento de elementos",
      "Conceitos de experiência do usuário",
      "Design adaptado voltado telas menores",
      "Eventos de clique",
      "Efeito de sombra em textos",
    ],
    components: [
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "ScrollView",
      "SafeAreaView",
      "StyleSheet",
      "NavigationContainer",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/piratas-do-caribe---filmes?platform=android",
  },
  {
    id: "2",
    name: "Formulário",
    images: [
      "formulario-1.jpg",
      "formulario-2.jpg",
      "formulario-3.jpg",
      "formulario-4.jpg",
    ],
    description:
      "Formulário com validação que recebe dados de um usuário (nome, ano de nascimento, endereço, CPF e RG. Após o formulário ser submitado, o usuário é redirecionado para a segunda tela do aplicativo, mostrando seus dados inseridos em formato de tabela, juntamento com sua idade, calculada a partir do ano de nascimento fornecido",
    technicals: [
      "Construção de formulários em React",
      "Uso de states para alterar componentes dinamicamente",
      "Validação de dados com REGEX (expressões regulares)",
      "Passagem de dados entre telas por meio de parâmetros de rota",
      "Fluxo de renderização",
      "Mensagens de alerta",
      "Renderização e estilização condicional",
      "Experiência de usuário no que diz respeito a preencher formulários em dispositivos móveis",
    ],
    components: [
      "StyleSheet",
      "View",
      "Text",
      "TextInput",
      "SafeAreaView",
      "TouchableOpacity",
      "TouchableWithoutFeedback",
      "Keyboard",
      "Alert",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/formulario?platform=android",
  },
  {
    id: "3",
    name: "RPG Card",
    images: ["rpg-card-1.jpg", "rpg-card-2.jpg"],
    description:
      "Card de personagem estilo RPG, contendo informações como nome, classe, nível, atributos de força, ataque, resistência e velociade. O card é adaptado para ser visualizado com a tela tanto em posição de paisagem quanto de retrato, podendo o usuário mudar para uma das duas posições ao pressionar o botão que contém uma seta",
    technicals: [
      "Estilização condicional",
      "Manipulação da orientação da tela com Expo",
      "Captura da largura e altura da tela do dispositivo",
      "Posição absoluta de elementos",
      "Flexbox para alinhamento de elementos",
      "Componentização do layout",
      "Separação de pastas para cada componente",
      "Ícones em React",
      "Passagem de dados entre componentes",
    ],
    components: [
      "StyleSheet",
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "useWindowDimensions",
      "ScreenOrientation",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/card-rpg?platform=android",
  },
  {
    id: "4",
    name: "Família Simpsons",
    images: [
      "familia-simpson-1.jpg",
      "familia-simpson-2.jpg",
      "familia-simpson-3.jpg",
      "familia-simpson-4.jpg",
      "familia-simpson-5.jpg",
      "familia-simpson-6.jpg",
    ],
    description:
      "Aplicativo mobile sobre os integrantes da família Simpson, apresentando informações descritivas da cada personagem (nome, gênero, idade e ocupação). O app somente possui 2 telas: uma que contém os cards referentes a cada Simpson, e outra que exibe os dados do personagem escolhido pelo usuário, que são renderizados dinamicamente",
    technicals: [
      "Renderização em lista com FlatList",
      "Uso da função map do JavaScript para renderizar itens dinamicamente",
      "Passagem de dados entre componentes através de propriedades e de parâmetros de rotas",
      "Conceito de elevação de state",
      "Cópia de dados de arrays para componentes usndo o spread operator",
      "Inserção de elementos filhos em um componente",
      "Estilização condicional a partir de propriedades de componentes",
      "Estilização da barra de status do dispositivo",
      "Consumo de dados de um arquivo JavaScript externo",
    ],
    components: [
      "FlatList",
      "StatusBar",
      "View",
      "Text",
      "TouchableOpacity",
      "Image",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/familia-simpson?platform=android",
  },
  {
    id: "5",
    name: "Card de apresentação",
    images: ["card-profissional-1.jpg", "card-profissional-2.jpg"],
    description:
      "Card de apresentação profissional de programador fictício. Inicialmente, o card exibe imagem, nome, e-mail e telefone de contato, porém ao clicar no botão de expandir, é acrescido as tecnologias (cada uma com uma respectiva cor) que o programador domina, além de botões de enviar mensagem e contratá-lo",
    technicals: [
      "Uso de funções para renderizações dinâmicas",
      "Passagem de funções entre componentes",
      "Uso de containers como componentes globais",
      "Imagens de Fundo em React",
      "Manipulação de opacidade de views",
      "Manipulação de overflow de elementos",
      "Desestruturação de objetos JavaScript",
      "Uso de bibliotecas para ícones",
    ],
    components: [
      "Image",
      "ImageBackground",
      "View",
      "Text",
      "TouchableOpacity",
      "StatusBar",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/profile-card?platform=android",
  },
  {
    id: "6",
    name: "Sistema Solar",
    images: [
      "solar-system-1.jpg",
      "solar-system-2.jpg",
      "solar-system-3.jpg",
      "solar-system-4.jpg",
      "solar-system-5.jpg",
      "solar-system-6.jpg",
      "solar-system-7.jpg",
    ],
    description:
      "Aplicativo que apresenta dados (nome, idade, quantidade de luas, temperatura ambiente) e informações pertinentes a respeito de cada planeta do nosso sistema solar. Na tela principal, o usuário pode escolher o planeta tanto pela imagem clicável, quanto pelo menu lateral que aparece quando o usuário clica no ícone de menu hambúrguer",
    technicals: [
      "Navegação por menu lateral",
      "Context API para compartilhar dados entre componentes",
      "Manipulação de contexts por hooks",
      "Uso de ícones vetorizadas disponibilizadas pelo próprio Expo",
      "Customização de menu lateral",
      "Combinação de múltiplas técnicas de navegação",
    ],
    components: [
      "DrawerNavigation",
      "createContext",
      "View",
      "Text",
      "TouchableOpacity",
      "FlatList",
      "StatusBar",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/profile-card?platform=android",
  },
  {
    id: "7",
    name: "Tela de animações",
    images: [
      "https://github.com/JohnPetros/omni-tech-industries-animation/raw/main/.github/omni-tech.gif",
    ],
    description:
      "Aplicativo que permite executar diferentes animações: Rotacionar (Rotate), Escalar (Scale), Trasnladar (Translate), Cisalhar (Skew), FadeIn e FadeOut em uma logo de uma empresa de tecnologia industrial",
    technicals: [
      "Gradiente de cor",
      "Animação nativa",
      "Interpolação de valores",
      "Pegar a altura do status bar do dispositivo",
      "Manipulação da propriedade transform de componentes",
    ],
    components: [
      "Animated",
      "Easing",
      "LinearGradient",
      "View",
      "Text",
      "TouchableOpacity",
      "StyleSheet",
    ],
    link: "https://snack.expo.dev/@git/github.com/JohnPetros/omni-tech-industries-animation?platform=web",
  },
  {
    id: "8",
    name: "Seleção brasileira 2022",
    images: [
      "https://github.com/JohnPetros/brazil-national-team-2022/raw/main/.github/brazil-national-team-2022.gif",
    ],
    description:
      "Aplicativo acerca dos jogadores da seleção brasileira da copa do mundo de 2022, apresentando informações como nome, altura, data de nascimento/idade, número de camiseta, clube e posição em que joga cada jogador",
    technicals: [
      "SVG em React Native",
      "Manipulação de data em JavaScript",
      "Listagem horizontal com FlatList",
      "Animações de entrada de componente na tela",
      "Renderização de imagens a partir de um link externo",
      "Instalação e utilização de bibliotecas externas",
    ],
    components: [
      "Animated",
      "FlatList",
      "View",
      "Text",
      "TouchableOpacity",
      "StyleSheet",
      "Image",
      "SafeAreaView",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/brazil-national-team-2022?platform=android",
  },
  {
    id: "9",
    name: "Multi calculadora",
    images: [
      "https://github.com/JohnPetros/multi-calculator/raw/main/.github/multi-calculator.gif",
      "https://github.com/JohnPetros/multi-calculator/raw/main/.github/currency-converter.jpeg",
      "https://github.com/JohnPetros/multi-calculator/raw/main/.github/length-converter.jpeg",
      "https://github.com/JohnPetros/multi-calculator/raw/main/.github/home.jpeg",
    ],
    description:
      "Aplicativo que consiste em uma calculadora convencional e um conversor para várias unidades (moeda, comprimento, área, massa, volume, temperatura, velocidade, temperatura, tempo, pressão, energia, ângulo e dados digitais), exibindo o cálculo em tempo real enquanto o usuário digita",
    technicals: [
      "Cálculo dinâmico de componentes a partir da largura da tela do dispositivo",
      "Funções para manipulação de arrays e validação de REGEX em JavaScript",
      "Utilização de design system em projetos",
    ],
    components: [
      "TextInput",
      "ScrollView",
      "View",
      "Text",
      "TouchableOpacity",
      "StyleSheet",
      "SafeAreaView",
    ],
    link: "https://snack.expo.dev/@joaopcarvalho/multi-calculator?platform=android",
  },
];
